name: 🚀 Production deployment
# Only trigger, when the build workflow succeeded
on:
  release:
    types:
      - created
  workflow_run:
    workflows: ["CICDPipeline"]
    types:
      - completed

env:
  AWS_REGION: us-east-2
  
jobs:
        
  buildingimage:
    name: Building container image
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Utilities
        run: |
          sudo apt-get update
          sudo apt-get install -y jq unzip
      - name: Install AWS Client
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install || true
          aws --version
          curl "https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/ghtsailctl" -o "dev"
          sudo mv "dev" "/usr/local/bin/dev"
          sudo chmod +x /usr/local/bin/dev
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
        
      - name: Build Docker Image
        run: docker build -t name_repo:latest .
      - name: Push image to container register
        run: |
            -docker push 111488783161.dkr.ecr.us-east-2.amazonaws.com/name_repo:latest
      - name: Deploying app to production
        
  on-failure:
    name: Cancelling deployment test failed
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Deploying app to production
        run: exit 1
